// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPTM7OWHJJXdxyTVG9sw9WZaR0H5ek9G4',
    appId: '1:295768825103:web:750f62d7f49db99245327a',
    messagingSenderId: '295768825103',
    projectId: 'alertify-4e7e6',
    authDomain: 'alertify-4e7e6.firebaseapp.com',
    storageBucket: 'alertify-4e7e6.appspot.com',
    measurementId: 'G-FK2QRHWXCN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAg72Nh19mId0epJstFSJ8_Rn0-vFNp5_o',
    appId: '1:295768825103:android:f8279f9e20f4415145327a',
    messagingSenderId: '295768825103',
    projectId: 'alertify-4e7e6',
    storageBucket: 'alertify-4e7e6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCikeUOUBF8ORo1i2O5NOy9NT1-VL4c7Tg',
    appId: '1:295768825103:ios:64609d6ddcaaa1cf45327a',
    messagingSenderId: '295768825103',
    projectId: 'alertify-4e7e6',
    storageBucket: 'alertify-4e7e6.appspot.com',
    iosBundleId: 'com.example.alertify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCikeUOUBF8ORo1i2O5NOy9NT1-VL4c7Tg',
    appId: '1:295768825103:ios:d115a33f32f83b4445327a',
    messagingSenderId: '295768825103',
    projectId: 'alertify-4e7e6',
    storageBucket: 'alertify-4e7e6.appspot.com',
    iosBundleId: 'com.example.alertify.RunnerTests',
  );
}
